import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { AuthProvider } from "../components/providers/auth-provider";
import { ThemeProvider } from "../components/providers/theme-provider";
import Loading from "@/app/loading";
import { ClientProviders } from "@/components/providers/client-providers";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { PageProvider } from "@/components/layout/main-layout";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={<Loading />}>
            <ReactQueryProvider>
              <ClientProviders>
                <AuthProvider>
                  <PageProvider>
                    {children}
                  </PageProvider>
                </AuthProvider>
              </ClientProviders>
            </ReactQueryProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}


